### PR TITLE
Remove old playbooks and roles from repo root

### PR DESCRIPTION
**Pull request by dometto**
Playbooks and roles were moved to the `playbooks` directory in https://github.com/UtrechtUniversity/researchcloud-items/commit/8fe250e85d77d0481b715d0a1da13368ce631dec, but the old files and `roles` directory were left in the repository root in case some component definitions on SRC still reference the old file paths. However, this results in a higher maintenance load (we have to update playbooks and roles in both locations). This PR removes the old files.

As discussed with @jelletreep, this may mean that any components that we have overlooked and that still reference the old path will fail to deploy. However, since this will only affect new workspaces, we think that's worth it -- it will also inform us that something needs to happen there. :)

I have made sure that:

1. the new location (`playbooks/...`) contains all definitions that exist in the old location
2. the new location always contains the newer version.
3. files in the old location were not updated after the files were copied to `playbooks/`
  * there was one file that *was* updated at a later date, but these changes were also made to the copies under `/playbooks`.

### CODE REVIEW

**Comment by dometto** [comment]
There is also still an `envs` directory in the repository root ([here](https://github.com/UtrechtUniversity/researchcloud-items/tree/main/envs)). Does anyone happen to know whether the definitions in that directory are still used for anything?

**Comment by jelletreep** [comment]
> There is also still an `envs` directory in the repository root ([here](https://github.com/UtrechtUniversity/researchcloud-items/tree/main/envs)). Does anyone happen to know whether the definitions in that directory are still used for anything?

Yes, those are requirements files that are used by the custom packages plugin (surf) to configure python environments. We could think of a better location for those files (but need to update the components then as well).

**Comment by jelletreep** [comment]
Great work! I would like to check some components that I think are important to see if the paths need to be updated. I will do so tomorrow

**Comment by dometto** [comment]
> I would like to check some components that I think are important to see if the paths need to be updated. I will do so tomorrow.

Great, thanks! Let me know if I can help check some of them.

**Comment by jelletreep** [comment]
@dometto, all checked, good to go!

**Comment by dometto** [comment]
Thanks!

**Pull request merged**
